name: CI
on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  build:
    continue-on-error: true
    runs-on: ${{ matrix.os_and_command.os }}
    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3', '3.4', 'ruby-head', 'truffleruby-head' ]
        gemfile: ["test/gemfiles/Gemfile.faraday-1", "test/gemfiles/Gemfile.faraday-2"]
        os_and_command:
        - os: 'macos-latest'
          command: 'env TESTOPTS="--verbose" bundle exec rake test'
        - os: ubuntu-latest
          # Sometimes minitest starts and then just hangs printing nothing.
          # Github by default kills after 6hours(!). Hopefully SIGTERM may let it print some details?
          command: 'timeout --signal=TERM 3m env TESTOPTS="--verbose" test/config/update_certs_k0s.rb'
        include:
        # run rubocop against lowest supported ruby
        - ruby: '3.1'
          gemfile: 'Gemfile'
          os_and_command:
            os: ubuntu-latest
            command: 'bundle exec rake rubocop'
    name: ${{ matrix.os_and_command.os }} ${{ matrix.ruby }} ${{ matrix.gemfile }} rake ${{ matrix.os_and_command.command }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v4
    # actions/setup-ruby did not support truffle or bundler caching
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false # disable running 'bundle install' and caching installed gems see https://github.com/httprb/http/issues/572
    - run: bundle install
    - run: ${{ matrix.os_and_command.command }}
    timeout-minutes: 10

