name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', 'truffleruby-head' ]
        os: ['ubuntu-latest', 'macos-latest']
        task: [test]
        include:
        # run rubocop against lowest supported ruby
        - os: ubuntu-latest
          ruby: '2.5'
          task: rubocop
    name: ${{ matrix.os }} ${{ matrix.ruby }} rake ${{ matrix.task }}
    steps:
    - uses: actions/checkout@v2
    # actions/setup-ruby did not support truffle or bundler caching
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install rake bundler
    - run: bundle exec rake ${{ matrix.task }}
